name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hey There"
      - name: Print goodby
        run: echo "I'm done.  See ya"
